Server:
  port: 9090

spring:
  application:
    name: msvc-course

  datasource:
    driver-class-name: com.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka