version: '3.9'

services:
  db_postgres:
    image: postgres:latest
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - ./tmp/db_postgres:/var/lib/postgresql/data
    networks:
      - srv_network
    restart: always

  db_mysql:
    image: mysql:latest
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./tmp/db_mysql:/var/lib/mysql
    networks:
      - srv_network
    restart: always

  app_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: app_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: strongpassword
    ports:
      - "5050:80"
    volumes:
      - ./tmp/app_pgadmin:/var/lib/pgadmin
    networks:
      - srv_network
    restart: always

  app_adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "5051:8080"
    networks:
      - srv_network
    restart: always

  srv_config:
    container_name: srv_config
    image: srv_config:1.0.0
    build: ./config/
    ports:
      - 8080:8080
    networks:
      - srv_network
    restart: always

  srv_eureka:
    container_name: srv_eureka
    image: srv_eureka:1.0.0
    build: ./eureka/
    ports:
      - 8761:8761
    networks:
      - srv_network
    restart: always

  srv_gateway:
    container_name: srv_gateway
    image: srv_gateway:1.0.0
    build: ./gateway/
    ports:
      - 8761:8761
    networks:
      - srv_network
    restart: always

  srv_student:
    container_name: srv_student
    image: srv_student:1.0.0
    build: ./student/
    ports:
      - 9091:9091
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db_mysql
      - srv_config
      - srv_eureka
      - srv_gateway
    networks:
      - srv_network
    restart: always

  srv_courses:
    container_name: srv_courses
    image: srv_courses:1.0.0
    build: ./course/
    ports:
      - 9091:9091
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db_mysql
      - srv_config
      - srv_eureka
      - srv_gateway
    networks:
      - srv_network
    restart: always

networks:
  srv_network:
    driver: bridge
