version: '3.9'

services:
  db_postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - ./tmp/db_postgres:/var/lib/postgresql/data
    networks:
      - srv_network
    restart: always

  db_mysql:
    image: mysql:latest
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./tmp/db_mysql:/var/lib/mysql
    networks:
      - srv_network
    restart: always

  app_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: app_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: strongpassword
    ports:
      - "5050:80"
    volumes:
      - ./tmp/app_pgadmin:/var/lib/pgadmin
    networks:
      - srv_network
    restart: always

  app_adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "5051:8080"
    networks:
      - srv_network
    restart: always

networks:
  srv_network:
    driver: bridge
