version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: strongpassword
    volumes:
      - ./tmp/mysql_data:/var/lib/mysql
    networks:
      - db_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: strongpassword
    ports:
      - "5050:80"
    volumes:
      - ./tmp/pgadmin_data:/var/lib/pgadmin
    networks:
      - db_network
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "5051:8080"
    networks:
      - db_network
    restart: always

networks:
  db_network:
    driver: bridge
